# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2021 ImmortalWrt.org

name: Build Base image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Base image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      
    steps:
      - name: Checkout docker repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64
          push: true
          tags: gustavo8000br:base
